import { buildGearAngles, deriveStartBands, gearRadius, mechanicalUniqueness, meshDistance, meshReport, scoreDifficulty, tautBandContacts, validateQuestion } from './gear-core.js';

const SVG_NS = 'http://www.w3.org/2000/svg';
const byId = id => document.getElementById(id);
const make = (name, attributes = {}) => { const node = document.createElementNS(SVG_NS, name); Object.entries(attributes).forEach(([key, value]) => node.setAttribute(key, value)); return node; };
const clamp = (value, min, max) => Math.min(max, Math.max(min, Number(value)));
const MESH_TOLERANCE = 10;

// 初始布局即为稳定的 3 × 3 啮合网：每个齿轮至少和一个邻居传动。
const starterGears = [
  ['g1', 210, 180], ['g2', 325, 180], ['g3', 440, 180],
  ['g4', 210, 295], ['g5', 325, 295], ['g6', 440, 295],
  ['g7', 210, 410], ['g8', 325, 410], ['g9', 440, 410],
].map(([id, x, y]) => ({ id, x, y, radius: gearRadius(24), teeth: 24, holeCount: 12, contacts: [] }));

let question = {
  gears: structuredClone(starterGears), driver: { id: 'g7', angle: 120 },
  pegs: [{ gearId: 'g1', hole: 2 }, { gearId: 'g2', hole: 8 }, { gearId: 'g5', hole: 4 }, { gearId: 'g8', hole: 9 }, { gearId: 'g7', hole: 1 }],
  bands: [{ id: 'band-1', name: '黄色橡皮筋', length: 860, points: [{ gearId: 'g1', hole: 2 }, { gearId: 'g2', hole: 8 }, { gearId: 'g5', hole: 4 }, { gearId: 'g8', hole: 9 }, { gearId: 'g7', hole: 1 }] }],
};
let selectedGearId = 'g5'; let activeBandId = 'band-1'; let simulationAngle = 0; let simulationGearId = 'g7'; let authorMode = 'pegs';
function gearById(id) { return question.gears.find(gear => gear.id === id); }
function pointAt(gear, hole, rotation = 0) { const angle = (hole / gear.holeCount) * Math.PI * 2 - Math.PI / 2 + rotation * Math.PI / 180; const radius = gear.radius - 16; return { x: gear.x + Math.cos(angle) * radius, y: gear.y + Math.sin(angle) * radius }; }
function gearPath(gear) { const points = []; const segments = gear.teeth * 4; for (let i = 0; i < segments; i += 1) { const tooth = i % 4; const radius = tooth === 1 || tooth === 2 ? gear.radius : gear.radius - 8; const angle = (i / segments) * Math.PI * 2 - Math.PI / 2; points.push(`${gear.x + Math.cos(angle) * radius},${gear.y + Math.sin(angle) * radius}`); } return points.join(' '); }
function bandColor(index) { return ['#f6c825', '#ff6b6b', '#4cd5e6', '#a98cff'][index % 4]; }
function normalizeDelta(value) { let delta = value; while (delta > 180) delta -= 360; while (delta < -180) delta += 360; return delta; }
function normalizeGearGeometry() { question.gears.forEach(gear => { gear.radius = gearRadius(gear.teeth); }); }
function gearStep(gear) { return 360 / gear.teeth; }
function snapToGearStep(angle, gear) { return Math.round(angle / gearStep(gear)) * gearStep(gear); }
function pegKey(peg) { return `${peg.gearId}:${peg.hole}`; }
function uniquePegs(pegs) { return [...new Map(pegs.map(peg => [pegKey(peg), peg])).values()]; }
function pointInPolygon(point, polygon) { let inside = false; for (let index = 0, previous = polygon.length - 1; index < polygon.length; previous = index++) { const a = polygon[index]; const b = polygon[previous]; const crosses = (a.y > point.y) !== (b.y > point.y) && point.x < (b.x - a.x) * (point.y - a.y) / (b.y - a.y) + a.x; if (crosses) inside = !inside; } return inside; }
function normalizeQuestion() { question.pegs = uniquePegs(question.pegs || question.bands.flatMap(band => band.points || [])); question.bands.forEach(band => { band.points ||= []; }); }
function assignContacts(report = meshReport(question.gears, MESH_TOLERANCE)) { question.gears.forEach(gear => { gear.contacts = report.contacts.get(gear.id) || []; }); return report; }
function snapGearToNearest(gear) { const nearest = question.gears.filter(other => other.id !== gear.id).sort((a, b) => Math.hypot(a.x - gear.x, a.y - gear.y) - Math.hypot(b.x - gear.x, b.y - gear.y))[0]; if (!nearest) return; const angle = Math.atan2(gear.y - nearest.y, gear.x - nearest.x) || 0; const distance = meshDistance(gear, nearest); gear.x = Math.round(nearest.x + Math.cos(angle) * distance); gear.y = Math.round(nearest.y + Math.sin(angle) * distance); }
function rebuildMesh(snapIsolated = false) { normalizeGearGeometry(); let report = assignContacts(); if (snapIsolated) for (let pass = 0; pass < 4 && report.isolated.length; pass += 1) { report.isolated.forEach(id => snapGearToNearest(gearById(id))); report = assignContacts(); } return report; }
function svgPoint(event, svg) { const rect = svg.getBoundingClientRect(); return { x: (event.clientX - rect.left) * 900 / rect.width, y: (event.clientY - rect.top) * 650 / rect.height }; }
function pointerAngle(event, svg, gear) { const point = svgPoint(event, svg); return Math.atan2(point.y - gear.y, point.x - gear.x) * 180 / Math.PI; }
function beginDriverTurn(event, svg, gear) { event.preventDefault(); simulationGearId = gear.id; selectedGearId = gear.id; const startAngle = pointerAngle(event, svg, gear); const origin = simulationAngle; const move = nextEvent => { simulationAngle = origin + normalizeDelta(pointerAngle(nextEvent, svg, gear) - startAngle); render(); }; const end = () => { simulationAngle = snapToGearStep(simulationAngle, gear); render(); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end); }
function beginGearMove(event, svg, gear) { if (event.target.classList.contains('hole')) return; event.preventDefault(); selectedGearId = gear.id; const start = svgPoint(event, svg); const origin = { x: gear.x, y: gear.y }; const move = nextEvent => { const point = svgPoint(nextEvent, svg); gear.x = Math.round(origin.x + point.x - start.x); gear.y = Math.round(origin.y + point.y - start.y); rebuildMesh(false); render(); }; const end = () => { rebuildMesh(true); render(); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end); }

function renderGear(svg, gear, { allowInput = false, rotation = 0, simulate = false } = {}) {
  const group = make('g', { class: `gear ${gear.id === selectedGearId ? 'is-selected' : ''} ${simulate ? 'is-driver' : ''}`, 'data-id': gear.id, transform: `rotate(${rotation} ${gear.x} ${gear.y})` }); group.append(make('polygon', { points: gearPath(gear), class: 'gear-tooth' })); group.append(make('circle', { cx: gear.x, cy: gear.y, r: gear.radius - 8, class: 'gear-body' }));
  for (let hole = 0; hole < gear.holeCount; hole += 1) { const point = pointAt(gear, hole); const dot = make('circle', { cx: point.x, cy: point.y, r: 5.5, class: 'hole', 'data-gear': gear.id, 'data-hole': hole }); if (allowInput) dot.addEventListener('click', click => { click.stopPropagation(); togglePeg(gear.id, hole); }); group.append(dot); }
  group.append(make('circle', { cx: gear.x, cy: gear.y, r: 12, class: 'axle' })); const label = make('text', { x: gear.x, y: gear.y + 4, 'text-anchor': 'middle', fill: '#314657', 'font-size': '11', 'font-weight': '700' }); label.textContent = gear.id.toUpperCase(); group.append(label); group.addEventListener('click', () => { selectedGearId = gear.id; render(); }); if (allowInput && authorMode !== 'draw') group.addEventListener('pointerdown', event => beginGearMove(event, svg, gear)); if (simulate) group.addEventListener('pointerdown', event => beginDriverTurn(event, svg, gear)); svg.append(group);
}
function renderPegs(svg, pegs, angles = new Map()) { pegs.forEach(peg => { const point = pointAt(gearById(peg.gearId), peg.hole, angles.get(peg.gearId) || 0); svg.append(make('circle', { cx: point.x, cy: point.y, r: 7, class: 'peg is-free' })); }); }
function renderBands(svg, bands, { angles = new Map(), initial = false } = {}) { bands.forEach((band, index) => { const pegs = band.points.map(point => ({ ...point, ...pointAt(gearById(point.gearId), point.hole, angles.get(point.gearId) || 0) })); if (pegs.length < 2) return; const contacts = tautBandContacts(pegs); if (contacts.length < 2) return; const closed = [...contacts, contacts[0]].map(point => `${point.x},${point.y}`).join(' '); svg.append(make('polyline', { points: closed, class: 'band-shadow', stroke: bandColor(index) }), make('polyline', { points: closed, class: 'band-line', stroke: bandColor(index) })); contacts.forEach(point => svg.append(make('circle', { cx: point.x, cy: point.y, r: 8, class: 'peg', fill: bandColor(index) }))); const tag = make('text', { x: contacts[0].x + 12, y: contacts[0].y - 11, class: 'band-label' }); tag.textContent = `${initial ? '初态' : '橡皮筋'} ${index + 1} · 接触 ${contacts.length}/${pegs.length} 钉`; svg.append(tag); }); }
function renderArrow(svg, angle = question.driver.angle) { const gear = gearById(question.driver.id); if (!gear) return; svg.append(make('path', { d: `M ${gear.x - 29} ${gear.y - 30} A 42 42 0 0 1 ${gear.x + 37} ${gear.y - 4}`, class: 'rotation-arrow' })); const text = make('text', { x: gear.x, y: gear.y + gear.radius + 18, 'text-anchor': 'middle', fill: '#ff8076', 'font-size': '12', 'font-weight': '700' }); text.textContent = `${angle}°`; svg.append(text); }
function renderDraft(svg) { const band = question.bands.find(candidate => candidate.id === activeBandId); if (!band?.draftPath?.length) return; svg.append(make('polyline', { points: band.draftPath.map(point => `${point.x},${point.y}`).join(' '), class: 'draft-line' })); }
function finishBandDraw(band) { const enclosed = question.pegs.filter(peg => pointInPolygon(pointAt(gearById(peg.gearId), peg.hole), band.draftPath)); band.points = enclosed; band.draftPath = []; authorMode = 'pegs'; render(); }
function beginBandDraw(event, svg) { if (authorMode !== 'draw') return; event.preventDefault(); const band = question.bands.find(candidate => candidate.id === activeBandId); if (!band) return; band.draftPath = [svgPoint(event, svg)]; const preview = make('polyline', { class: 'draft-line', points: '' }); svg.append(preview); const move = nextEvent => { band.draftPath.push(svgPoint(nextEvent, svg)); preview.setAttribute('points', band.draftPath.map(point => `${point.x},${point.y}`).join(' ')); }; const end = () => { if (band.draftPath.length > 2) finishBandDraw(band); else { band.draftPath = []; authorMode = 'pegs'; render(); } window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end); }
function renderBoard(elementId, bands, { allowInput = false, angles = new Map(), simulation = false, pegs = [] } = {}) { const svg = byId(elementId); svg.replaceChildren(); const defs = make('defs'); const marker = make('marker', { id: `${elementId}-arrowhead`, markerWidth: 8, markerHeight: 8, refX: 7, refY: 3, orient: 'auto' }); marker.append(make('path', { d: 'M0,0 L0,6 L8,3 z', fill: '#ef4c45' })); defs.append(marker); svg.append(defs); question.gears.forEach(gear => renderGear(svg, gear, { allowInput, rotation: angles.get(gear.id) || 0, simulate: simulation })); renderPegs(svg, pegs, angles); renderBands(svg, bands, { angles, initial: simulation }); if (allowInput) { renderArrow(svg); renderDraft(svg); svg.addEventListener('pointerdown', event => beginBandDraw(event, svg)); } }

function renderControls() { byId('driver-gear').innerHTML = question.gears.map(gear => `<option value="${gear.id}">${gear.id.toUpperCase()} · ${gear.teeth} 齿</option>`).join(''); byId('driver-gear').value = question.driver.id; byId('driver-direction').value = question.driver.angle >= 0 ? '1' : '-1'; byId('driver-angle').value = Math.abs(question.driver.angle); byId('author-angle').value = question.driver.angle; const gear = gearById(selectedGearId); byId('selected-gear-label').textContent = gear ? `已选中 ${gear.id.toUpperCase()} · 统一齿距下外径自动计算` : '点击齿轮进行编辑'; const container = byId('gear-fields'); container.className = gear ? '' : 'disabled-fields'; const toothOptions = [12, 16, 20, 24].map(count => `<option value="${count}" ${gear?.teeth === count ? 'selected' : ''}>${count} 齿</option>`).join(''); container.innerHTML = gear ? `<div class="two-columns"><label>X 位置<input data-field="x" type="number" value="${gear.x}" /></label><label>Y 位置<input data-field="y" type="number" value="${gear.y}" /></label></div><div class="two-columns"><label>外径（自动）<output>${Math.round(gear.radius * 2)} px</output></label><label>齿数<select data-field="teeth">${toothOptions}</select></label></div><label>外圈孔位数<input data-field="holeCount" type="number" min="6" max="24" value="${gear.holeCount}" /></label><p class="helper">当前啮合：${gear.contacts.map(id => id.toUpperCase()).join(' · ') || '拖动结束后自动回吸'}</p>` : ''; container.querySelectorAll('input, select').forEach(input => input.addEventListener('change', () => { if (input.dataset.field === 'teeth') gear.teeth = Number(input.value); else gear[input.dataset.field] = clamp(input.value, 0, input.dataset.field === 'holeCount' ? 24 : 900); rebuildMesh(true); render(); })); }
function renderBandsList() { byId('band-list').replaceChildren(...question.bands.map((band, index) => { const item = document.createElement('article'); item.className = `band-item ${band.id === activeBandId ? 'is-active' : ''}`; item.innerHTML = `<strong>${band.name || `橡皮筋 ${index + 1}`}</strong><div class="band-meta"><span>${band.points.length} 个围入钢钉</span><span>${band.length} mm</span></div><label>长度 mm<input class="band-length" type="number" min="100" step="10" value="${band.length}" /></label><div class="band-actions"><button class="mini-button remove-point">撤销上一枚钢钉</button><button class="mini-button remove-band">删除橡皮筋</button></div>`; item.addEventListener('click', () => { activeBandId = band.id; render(); }); item.querySelector('.band-length').addEventListener('input', event => { band.length = Number(event.target.value); render(); }); item.querySelector('.remove-point').addEventListener('click', event => { event.stopPropagation(); band.points.pop(); render(); }); item.querySelector('.remove-band').addEventListener('click', event => { event.stopPropagation(); question.bands = question.bands.filter(candidate => candidate.id !== band.id); activeBandId = question.bands[0]?.id || null; render(); }); return item; })); }
function renderReport() { const mesh = rebuildMesh(false); const validation = validateQuestion(question); const difficulty = scoreDifficulty(question); const unique = validation.valid && !mesh.isolated.length ? mechanicalUniqueness(question) : { unique: false, reason: mesh.isolated.length ? `齿轮 ${mesh.isolated.map(id => id.toUpperCase()).join('、')} 未啮合。` : '先修复题目配置错误。' }; byId('difficulty-rating').textContent = difficulty.rating; byId('difficulty-raw').textContent = `${difficulty.raw} 难度分`; byId('difficulty-list').innerHTML = `<dt>参与齿轮</dt><dd>${difficulty.activeGearCount} / ${question.gears.length}</dd><dt>传动齿轮</dt><dd>${difficulty.drivenGearCount}</dd><dt>钢钉节点</dt><dd>${difficulty.pegCount}</dd><dt>闭合橡皮筋</dt><dd>${difficulty.bandCount}</dd><dt>孔位精度</dt><dd>${difficulty.anglePrecision}° / 孔</dd>`; const uniqueBox = byId('uniqueness'); uniqueBox.textContent = unique.unique ? `机械唯一性通过：${unique.reason}` : `不可发布：${unique.reason}`; uniqueBox.style.background = unique.unique ? '#eef6f2' : '#fff0ed'; uniqueBox.style.color = unique.unique ? '#176a51' : '#a53c35'; const errors = [...validation.errors, ...mesh.isolated.map(id => `${id.toUpperCase()} 没有与任何齿轮啮合。`)]; byId('validation').innerHTML = errors.map(error => `<li>${error}</li>`).join(''); byId('publish').disabled = !validation.valid || !unique.unique; byId('target-status').textContent = validation.valid && !mesh.isolated.length ? `已配置 ${question.bands.length} 根闭合橡皮筋` : '等待完成出题配置'; }
function render() { normalizeQuestion(); renderControls(); renderBandsList(); const targetAngles = buildGearAngles(question.gears, question.driver.id, question.driver.angle); renderBoard('target-board', question.bands, { allowInput: true, angles: targetAngles, pegs: question.pegs }); const answer = deriveStartBands(question); const answerPegs = uniquePegs(answer.flatMap(band => band.points)); const simulationGear = gearById(simulationGearId) || gearById(question.driver.id); const angles = buildGearAngles(question.gears, simulationGear.id, simulationAngle); renderBoard('player-board', [], { angles, simulation: true, pegs: [] }); renderBoard('answer-board', answer, { simulation: true, pegs: answerPegs }); byId('simulation-angle').textContent = `${simulationGear.id.toUpperCase()} · ${simulationAngle.toFixed(1)}° · 每格 ${gearStep(simulationGear).toFixed(1)}°`; byId('initial-note').textContent = `此盘面从空白开始。可操作任意齿轮：拖动后会吸附到整齿位置，或用“一格”按钮联动整个传动网。题目终态为 ${question.driver.id.toUpperCase()} ${question.driver.angle >= 0 ? '顺' : '逆'}时针 ${Math.abs(question.driver.angle)}°。`; renderReport(); }
function togglePeg(gearId, hole) { if (authorMode !== 'pegs') return; const key = `${gearId}:${hole}`; const index = question.pegs.findIndex(peg => pegKey(peg) === key); if (index >= 0) question.pegs.splice(index, 1); else question.pegs.push({ gearId, hole }); render(); }
function autoMesh() { rebuildMesh(true); render(); }
function exportQuestion() { const payload = { schemaVersion: 1, question, derivedStart: deriveStartBands(question), difficulty: scoreDifficulty(question), mechanicalUniqueness: mechanicalUniqueness(question) }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const link = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: '牵线成形-题目.json' }); link.click(); URL.revokeObjectURL(link.href); }
async function importQuestion(file) { const payload = JSON.parse(await file.text()); question = payload.question || payload; normalizeQuestion(); selectedGearId = question.gears[0]?.id; activeBandId = question.bands[0]?.id; simulationGearId = question.driver.id; simulationAngle = 0; rebuildMesh(true); render(); }
function stepSimulation(direction) { const gear = gearById(simulationGearId) || gearById(question.driver.id); simulationGearId = gear.id; simulationAngle = snapToGearStep(simulationAngle + direction * gearStep(gear), gear); render(); }
function stepAuthor(direction) { const gear = gearById(question.driver.id); question.driver.angle = snapToGearStep(question.driver.angle + direction * gearStep(gear), gear); render(); }
byId('driver-gear').addEventListener('change', event => { question.driver.id = event.target.value; render(); }); byId('driver-direction').addEventListener('change', event => { question.driver.angle = Math.abs(question.driver.angle) * Number(event.target.value); render(); }); byId('driver-angle').addEventListener('input', event => { question.driver.angle = Math.abs(Number(event.target.value)) * Number(byId('driver-direction').value); render(); }); byId('author-angle').addEventListener('input', event => { question.driver.angle = clamp(event.target.value, -720, 720); render(); }); byId('author-step-back').addEventListener('click', () => stepAuthor(-1)); byId('author-step-forward').addEventListener('click', () => stepAuthor(1)); byId('author-reset').addEventListener('click', () => { question.driver.angle = 0; render(); }); byId('auto-mesh').addEventListener('click', autoMesh); byId('peg-mode').addEventListener('click', () => { authorMode = 'pegs'; render(); }); byId('reset-simulation').addEventListener('click', () => { simulationGearId = question.driver.id; simulationAngle = 0; render(); }); byId('finish-simulation').addEventListener('click', () => { simulationGearId = question.driver.id; simulationAngle = question.driver.angle; render(); }); byId('step-back').addEventListener('click', () => stepSimulation(-1)); byId('step-forward').addEventListener('click', () => stepSimulation(1)); byId('new-band').addEventListener('click', () => { const id = `band-${Date.now()}`; question.bands.push({ id, name: `橡皮筋 ${question.bands.length + 1}`, length: 600, points: [], draftPath: [] }); activeBandId = id; authorMode = 'draw'; render(); }); byId('export').addEventListener('click', exportQuestion); byId('publish').addEventListener('click', exportQuestion); byId('import').addEventListener('change', event => { if (event.target.files[0]) importQuestion(event.target.files[0]); });
rebuildMesh(true); render();
